services:
  postgres:
    image: pgvector/pgvector:pg17
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3000"]
    ports:
      - 3000:3000
    depends_on:
      - postgres
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    command: ["python", "runner.py", "bot"]
    depends_on:
      - postgres
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    command: ["python", "-m", "pgqueuer", "run", "app.workers.run_worker"]
    depends_on:
      - postgres
    deploy:
      replicas: 2
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
  
volumes:
  db_data:
