"""'add separate summary field to resume model'

Revision ID: 0164bb7e4683
Revises: 16b0f5c0ff39
Create Date: 2024-10-13 23:49:57.370194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0164bb7e4683"
down_revision: Union[str, None] = "16b0f5c0ff39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resumes", sa.Column("summary", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "summary")
    # ### end Alembic commands ###
