"""'add more resume fields'

Revision ID: 16b0f5c0ff39
Revises: dc628b7dca36
Create Date: 2024-10-13 23:13:54.806620

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16b0f5c0ff39"
down_revision: Union[str, None] = "dc628b7dca36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resumes", sa.Column("yoe", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_resumes_yoe"), "resumes", ["yoe"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resumes_yoe"), table_name="resumes")
    op.drop_column("resumes", "yoe")
    # ### end Alembic commands ###
