"""'user preferred work type'

Revision ID: 2645a37e0da4
Revises: c55368ca8ea7
Create Date: 2024-10-16 11:04:45.108565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "2645a37e0da4"
down_revision: Union[str, None] = "c55368ca8ea7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    preferred_work_type_enum = postgresql.ENUM(
        "IN_OFFICE", "HYBRID", "REMOTE", name="preferredworktype"
    )
    preferred_work_type_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_seekers",
        sa.Column(
            "preferred_work_type",
            sa.Enum("IN_OFFICE", "HYBRID", "REMOTE", name="preferredworktype"),
            nullable=False,
            server_default="IN_OFFICE",
        ),
    )
    op.create_index(
        op.f("ix_job_seekers_preferred_work_type"),
        "job_seekers",
        ["preferred_work_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_seekers_preferred_work_type"), table_name="job_seekers")
    op.drop_column("job_seekers", "preferred_work_type")
    # ### end Alembic commands ###
