"""'add salary fields'

Revision ID: 2d46b246a111
Revises: 96b3494740cd
Create Date: 2024-10-17 03:55:09.442247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d46b246a111'
down_revision: Union[str, None] = '96b3494740cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('salary', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('median_salary', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('estimated_salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'estimated_salary')
    op.drop_column('vacancies', 'median_salary')
    op.drop_column('vacancies', 'salary')
    # ### end Alembic commands ###
