"""'add role field'

Revision ID: 4e1455dfd9f9
Revises: 2d46b246a111
Create Date: 2024-10-17 04:06:41.617187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1455dfd9f9'
down_revision: Union[str, None] = '2d46b246a111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('role', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'role')
    # ### end Alembic commands ###
