"""'resume estimated salary'

Revision ID: 7c3f5bb2d3d4
Revises: 2645a37e0da4
Create Date: 2024-10-16 11:12:53.440168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c3f5bb2d3d4"
down_revision: Union[str, None] = "2645a37e0da4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resumes", sa.Column("estimated_salary", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "estimated_salary")
    # ### end Alembic commands ###
