"""'add new vacancy fields'

Revision ID: 96b3494740cd
Revises: c6833f688786
Create Date: 2024-10-17 03:19:26.967258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b3494740cd'
down_revision: Union[str, None] = 'c6833f688786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('location', sa.String(length=256), nullable=True))
    op.add_column('vacancies', sa.Column('required_years_of_experience', sa.Integer(), nullable=True))
    op.add_column('vacancies', sa.Column('seniority', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'seniority')
    op.drop_column('vacancies', 'required_years_of_experience')
    op.drop_column('vacancies', 'location')
    # ### end Alembic commands ###
