"""'add requirements embedding field'

Revision ID: a5b64c04be44
Revises: 4e1455dfd9f9
Create Date: 2024-10-17 04:43:02.250678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a5b64c04be44'
down_revision: Union[str, None] = '4e1455dfd9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('requirements_embedding', pgvector.sqlalchemy.VECTOR(dim=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'requirements_embedding')
    # ### end Alembic commands ###
