"""'add embedding fields to resume'

Revision ID: c55368ca8ea7
Revises: 0164bb7e4683
Create Date: 2024-10-14 17:42:57.618226

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import pgvector

# revision identifiers, used by Alembic.
revision: str = "c55368ca8ea7"
down_revision: Union[str, None] = "0164bb7e4683"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resumes",
        sa.Column(
            "skills_embeddings", pgvector.sqlalchemy.VECTOR(dim=1024), nullable=True
        ),
    )
    op.add_column(
        "resumes",
        sa.Column(
            "content_embedding", pgvector.sqlalchemy.VECTOR(dim=1024), nullable=True
        ),
    )
    op.drop_column("resumes", "embedding")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resumes",
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("resumes", "content_embedding")
    op.drop_column("resumes", "skills_embeddings")
    # ### end Alembic commands ###
