"""'add company manager'

Revision ID: c6833f688786
Revises: 7c3f5bb2d3d4
Create Date: 2024-10-17 02:05:44.880236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6833f688786'
down_revision: Union[str, None] = '7c3f5bb2d3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_managers_token'), 'managers', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managers_token'), table_name='managers')
    op.drop_table('managers')
    # ### end Alembic commands ###
