"""'status and location fields in job seeker model'

Revision ID: dc628b7dca36
Revises: ea0f53053820
Create Date: 2024-10-13 18:12:45.617512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "dc628b7dca36"
down_revision: Union[str, None] = "ea0f53053820"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_status_enum = postgresql.ENUM(
        "PENDING", "ACTIVE", "INACTIVE", name="userstatus"
    )
    user_status_enum.create(op.get_bind())

    op.add_column(
        "job_seekers",
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACTIVE", "INACTIVE", name="userstatus"),
            nullable=False,
        ),
    )
    op.add_column("job_seekers", sa.Column("location", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_job_seekers_location"), "job_seekers", ["location"], unique=False
    )
    op.create_index(
        op.f("ix_job_seekers_status"), "job_seekers", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_job_seekers_status"), table_name="job_seekers")
    op.drop_index(op.f("ix_job_seekers_location"), table_name="job_seekers")
    op.drop_column("job_seekers", "location")
    op.drop_column("job_seekers", "status")
    # ### end Alembic commands ###
